- name: time_series_forecast_agent
  _target_: recipe.time_series_forecast.time_series_forecast_agent_flow.TimeSeriesForecastAgentFlow
  max_steps: 3
  max_parallel_calls: 5
  lookback_window: 168
  forecast_horizon: 24
